import {PrismaClient} from '@prisma/client';import {hash} from 'bcryptjs';import {rolePermissions} from '../src/policy';
const db=new PrismaClient();
async function seed(){for(const [name,permissions] of Object.entries(rolePermissions)){const role=await db.role.upsert({where:{name},create:{name},update:{}});for(const name of permissions){const permission=await db.permission.upsert({where:{name},create:{name},update:{}});await db.rolePermission.upsert({where:{roleId_permissionId:{roleId:role.id,permissionId:permission.id}},create:{roleId:role.id,permissionId:permission.id},update:{}})}}
 const categories=[['سیاست','politics'],['اقتصاد','economy'],['جامعه','society'],['فناوری','technology'],['بین‌الملل','international'],['فرهنگ','culture']];for(const [name,slug] of categories)await db.category.upsert({where:{slug},update:{},create:{name,slug}});
 for(const name of ['مدیریت','تحریریه','خبرنگاری','روابط عمومی','فنی','پشتیبانی'])await db.department.upsert({where:{name},update:{},create:{name}});
 for(const plan of [{id:'monthly',name:'ماهانه',months:1,amount:1490000},{id:'quarterly',name:'سه‌ماهه',months:3,amount:3990000},{id:'yearly',name:'سالانه',months:12,amount:13900000}])await db.vipPlan.upsert({where:{id:plan.id},update:{},create:plan});
 await db.setting.upsert({where:{key:'brand'},update:{},create:{key:'brand',value:{name:'KhabarFori',locale:'fa',direction:'rtl'}}});
 if(process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD){if(process.env.ADMIN_PASSWORD.length<16||Buffer.byteLength(process.env.ADMIN_PASSWORD)>72)throw Error('ADMIN_PASSWORD must be 16+ characters and at most 72 UTF-8 bytes');const role=await db.role.findUniqueOrThrow({where:{name:'SUPER_ADMIN'}});const exists=await db.user.findUnique({where:{email:process.env.ADMIN_EMAIL.toLowerCase()}});if(!exists)await db.user.create({data:{email:process.env.ADMIN_EMAIL.toLowerCase(),name:'مدیر سامانه',passwordHash:await hash(process.env.ADMIN_PASSWORD,12),roles:{create:{roleId:role.id}}}})}
 if(process.env.SEED_DEMO==='true'&&process.env.ADMIN_EMAIL){const author=await db.user.findUniqueOrThrow({where:{email:process.env.ADMIN_EMAIL.toLowerCase()}});const category=await db.category.findUniqueOrThrow({where:{slug:'technology'}});if(await db.news.count()===0)await db.news.create({data:{title:'به اتاق خبر خبرفوری خوش آمدید',description:'اولین خبر نمونه برای بررسی گردش کار تحریریه',content:'این یک محتوای نمونه برای بررسی سامانه است و خبر واقعی محسوب نمی‌شود. خبر را ویرایش کنید و از بخش مدیریت، محتوای رسانه خود را منتشر کنید.',categoryId:category.id,authorId:author.id,status:'PUBLISHED',publishedAt:new Date(),featured:true}});const department=await db.department.findUniqueOrThrow({where:{name:'تحریریه'}});if(await db.employee.count()===0)await db.employee.create({data:{fullName:'همکار نمونه',position:'دبیر تحریریه',departmentId:department.id,biography:'پروفایل نمونه؛ پیش از انتشار عمومی جایگزین شود.',email:'editor@example.com',employeeCode:'KF-DEMO-001',employmentDate:new Date(),status:'ACTIVE'}})}

}
seed().finally(()=>db.$disconnect());
