import {Injectable,ServiceUnavailableException,BadRequestException,Controller,Post,Get,Req,Body,Headers,UploadedFile,UseInterceptors,ForbiddenException} from '@nestjs/common';
import {FileInterceptor} from '@nestjs/platform-express';
import {createClient} from '@supabase/supabase-js';
import {createHmac,timingSafeEqual,randomUUID} from 'node:crypto';
import {initializeApp,applicationDefault,getApps} from 'firebase-admin/app';import {getMessaging} from 'firebase-admin/messaging';
import {Db} from './db';import {Permit,Public} from './security';import {CheckoutDto} from './dto';import {addMonthsClamped} from './policy';
export interface SocialProvider{topics(since:Date):Promise<{tag:string;mentions:number;engagement:number}[]>}
@Injectable()
export class NotificationService{constructor(private db:Db){}async send(userId:string,title:string,body:string){const record=await this.db.notification.create({data:{userId,title,body}});if(!process.env.GOOGLE_APPLICATION_CREDENTIALS)return record;if(!getApps().length)initializeApp({credential:applicationDefault()});const tokens=await this.db.device.findMany({where:{userId},take:500});if(tokens.length){const result=await getMessaging().sendEachForMulticast({tokens:tokens.map(t=>t.token),notification:{title,body}});for(let i=0;i<result.responses.length;i++)if(result.responses[i].error?.code==='messaging/registration-token-not-registered')await this.db.device.delete({where:{id:tokens[i].id}})}return record}}
@Injectable()
export class PaymentService{
 constructor(private db:Db){}
 configured(){if(!process.env.PAYMENT_API_URL||!process.env.PAYMENT_API_KEY||!process.env.PAYMENT_WEBHOOK_SECRET)throw new ServiceUnavailableException('درگاه پرداخت پیکربندی نشده است.');}
 async provider(path:string,body:unknown){this.configured();const r=await fetch(process.env.PAYMENT_API_URL!.replace(/\/$/,'')+path,{method:'POST',headers:{Authorization:'Bearer '+process.env.PAYMENT_API_KEY,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new ServiceUnavailableException('درگاه پاسخ معتبر نداد.');return r.json() as Promise<any>}
 async checkout(userId:string,planId:string,key:string){this.configured();if(!/^[a-zA-Z0-9_-]{16,128}$/.test(key))throw new BadRequestException('Idempotency-Key is required');const plan=await this.db.vipPlan.findUnique({where:{id:planId}});if(!plan?.active)throw new BadRequestException();const existing=await this.db.payment.findUnique({where:{idempotencyKey:key}});if(existing&&(existing.userId!==userId||existing.planId!==planId))throw new BadRequestException('Idempotency conflict');const payment=existing||await this.db.payment.create({data:{userId,planId,amount:plan.amount,currency:plan.currency,idempotencyKey:key}});if(payment.status==='VERIFIED')return {paymentId:payment.id,status:'VERIFIED'};const result=await this.provider('/checkout',{paymentId:payment.id,amount:payment.amount,currency:payment.currency,idempotencyKey:key,callbackUrl:process.env.PAYMENT_CALLBACK_URL});if(typeof result.reference!=='string'||typeof result.url!=='string'||!result.url.startsWith('https://'))throw new ServiceUnavailableException('Invalid checkout response');await this.db.payment.update({where:{id:payment.id},data:{providerReference:result.reference}});return {paymentId:payment.id,url:result.url}}
 async webhook(raw:Buffer,signature:string){this.configured();const expected=createHmac('sha256',process.env.PAYMENT_WEBHOOK_SECRET!).update(raw).digest('hex');if(!/^[a-f0-9]{64}$/i.test(signature)||!timingSafeEqual(Buffer.from(signature,'hex'),Buffer.from(expected,'hex')))throw new ForbiddenException();let event:any;try{event=JSON.parse(raw.toString())}catch{throw new BadRequestException()};if(typeof event.reference!=='string')throw new BadRequestException();const p=await this.db.payment.findUnique({where:{providerReference:event.reference},include:{plan:true}});if(!p)throw new BadRequestException();const verified=await this.provider('/verify',{reference:p.providerReference,paymentId:p.id});if(verified.status!=='paid'||verified.amount!==p.amount||verified.currency!==p.currency||verified.reference!==p.providerReference||typeof verified.transactionId!=='string')throw new BadRequestException('Payment verification mismatch');return this.db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM users WHERE id=${p.userId}::uuid FOR UPDATE`;const latest=await tx.payment.findUniqueOrThrow({where:{id:p.id}});if(latest.status==='VERIFIED')return {ok:true};await tx.payment.update({where:{id:p.id},data:{status:'VERIFIED',verifiedAt:new Date(),transactionId:verified.transactionId}});const active=await tx.subscription.findFirst({where:{userId:p.userId,expiresAt:{gt:new Date()}},orderBy:{expiresAt:'desc'}});const start=active?.expiresAt||new Date();await tx.subscription.create({data:{userId:p.userId,planId:p.planId,paymentId:p.id,startsAt:start,expiresAt:addMonthsClamped(start,p.plan.months)}});return {ok:true}})}
}
@Controller('subscriptions')
export class SubscriptionController{constructor(private payments:PaymentService,private db:Db){}
 @Public() @Get('plans') plans(){return this.db.vipPlan.findMany({where:{active:true},orderBy:{months:'asc'}})}
 @Get('status') status(@Req() req:any){return this.db.subscription.findFirst({where:{userId:req.user.id,startsAt:{lte:new Date()},expiresAt:{gt:new Date()}},orderBy:{expiresAt:'desc'}})}
 @Get('payments') history(@Req() req:any){return this.db.payment.findMany({where:{userId:req.user.id},orderBy:{createdAt:'desc'},take:100})}
 @Post('checkout') checkout(@Req() req:any,@Body() d:CheckoutDto,@Headers('idempotency-key') key:string){return this.payments.checkout(req.user.id,d.planId,key)}
 @Public() @Post('webhook') webhook(@Req() req:any,@Headers('x-payment-signature') sig:string){if(!req.rawBody)throw new BadRequestException();return this.payments.webhook(req.rawBody,sig||'')}
}
export function detectImage(buffer:Buffer){if(buffer.length>=3&&buffer[0]===0xff&&buffer[1]===0xd8&&buffer[2]===0xff)return {mime:'image/jpeg',ext:'jpg'};if(buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return {mime:'image/png',ext:'png'};if(buffer.subarray(0,4).toString()==='RIFF'&&buffer.subarray(8,12).toString()==='WEBP')return {mime:'image/webp',ext:'webp'};return null}
@Controller('media')
export class MediaController{
 @Permit('news:write') @Post() @UseInterceptors(FileInterceptor('file',{limits:{fileSize:5*1024*1024,files:1}}))
 async upload(@UploadedFile() file:Express.Multer.File,@Req() req:any){if(!file)throw new BadRequestException('فایل لازم است.');const detected=detectImage(file.buffer);if(!detected||detected.mime!==file.mimetype)throw new BadRequestException('فقط تصاویر JPEG، PNG و WebP مجاز هستند.');if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY)throw new ServiceUnavailableException('ذخیره‌سازی رسانه پیکربندی نشده است.');const client=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY);const path=`${req.user.id}/${randomUUID()}.${detected.ext}`;const bucket=process.env.SUPABASE_MEDIA_BUCKET||'news-covers';const {error}=await client.storage.from(bucket).upload(path,file.buffer,{contentType:detected.mime,upsert:false,cacheControl:'31536000'});if(error)throw new ServiceUnavailableException('بارگذاری انجام نشد.');return {path,url:client.storage.from(bucket).getPublicUrl(path).data.publicUrl}}
}
