import {Injectable,Controller,Get,Post,Patch,Delete,Param,Query,Req,Body,NotFoundException,ForbiddenException,BadRequestException,ParseUUIDPipe} from '@nestjs/common';
import {Db} from './db';import {Public,Permit,Principal} from './security';import {NewsDto,CommentDto} from './dto';import {hasPermission,canReadPremium} from './policy';
const relations={category:true,author:{select:{name:true}},tags:{include:{tag:true}}} as const;
export const newsSummary={id:true,title:true,description:true,coverImage:true,category:true,author:{select:{name:true}},authorId:true,tags:{include:{tag:true}},status:true,vip:true,kind:true,views:true,publishedAt:true,createdAt:true} as const;
export function presentNews(n:any){return {...n,category:n.category.name,author:n.author.name,tags:n.tags.map((t:any)=>t.tag.name)}}
@Injectable()
export class NewsService{
 constructor(private db:Db){}
 async premium(user?:Principal){if(!user)return false;if(hasPermission(user.permissions,'news:publish'))return true;const sub=await this.db.subscription.findFirst({where:{userId:user.id,startsAt:{lte:new Date()},expiresAt:{gt:new Date()}},orderBy:{expiresAt:'desc'}});return canReadPremium(sub?.expiresAt||null)}
 async list(q:any,user?:Principal){const take=Math.min(Math.max(Number(q.limit)||20,1),100),internal=q.internal==='true'&&user&&(hasPermission(user.permissions,'news:read-internal')||hasPermission(user.permissions,'news:write'));const where:any={status:internal?{not:'ARCHIVED'}:'PUBLISHED'};if(internal&&!hasPermission(user!.permissions,'news:read-internal'))where.authorId=user!.id;if(q.category)where.category={name:q.category};if(q.q)where.OR=[{title:{contains:String(q.q).slice(0,200),mode:'insensitive'}},{description:{contains:String(q.q).slice(0,200),mode:'insensitive'}}];if(q.vip==='true')where.vip=true;
 const items=await this.db.news.findMany({where,select:newsSummary,orderBy:[{createdAt:'desc'},{id:'desc'}],take:take+1,...(q.cursor?{cursor:{id:q.cursor},skip:1}:{})});const hasMore=items.length>take;return {items:items.slice(0,take).map(presentNews),nextCursor:hasMore?items[take-1].id:null};}
 async detail(id:string,user?:Principal){const n=await this.db.news.findUnique({where:{id},include:relations});if(!n||n.status==='ARCHIVED')throw new NotFoundException();const editor=!!user&&(hasPermission(user.permissions,'news:read-internal')||n.authorId===user.id&&hasPermission(user.permissions,'news:write'));if(n.status!=='PUBLISHED'&&!editor)throw new NotFoundException();const allowed=!n.vip||editor||await this.premium(user);return {...presentNews(n),content:allowed?n.content:'',locked:!allowed}}
 async write(dto:NewsDto,user:Principal,id?:string){if(dto.status==='PUBLISHED'&&!hasPermission(user.permissions,'news:publish'))throw new ForbiddenException('انتشار خبر نیازمند تایید سردبیر است.');if(id){const previous=await this.db.news.findUnique({where:{id}});if(!previous)throw new NotFoundException();if(!hasPermission(user.permissions,'news:publish')&&(previous.authorId!==user.id||previous.status==='PUBLISHED'))throw new ForbiddenException();}
 if(dto.coverImage&&(!process.env.SUPABASE_URL||!dto.coverImage.startsWith(process.env.SUPABASE_URL+'/storage/v1/object/')))throw new BadRequestException('تصویر باید از فضای ذخیره‌سازی سامانه باشد.');const {category,tags,...fields}=dto;const cat=await this.db.category.findUnique({where:{name:category}});if(!cat)throw new BadRequestException('دسته‌بندی معتبر نیست.');return this.db.$transaction(async tx=>{const data={...fields,vip:fields.kind&&fields.kind!=='NEWS'?true:fields.vip,categoryId:cat.id,publishedAt:dto.status==='PUBLISHED'?new Date():null};const n=id?await tx.news.update({where:{id},data}):await tx.news.create({data:{...data,authorId:user.id}});await tx.newsTag.deleteMany({where:{newsId:n.id}});for(const name of [...new Set(tags)]){const tag=await tx.tag.upsert({where:{name},update:{},create:{name}});await tx.newsTag.create({data:{newsId:n.id,tagId:tag.id}})}await tx.analytics.create({data:{event:id?'news.updated':'news.created',userId:user.id,newsId:n.id,metadata:{status:n.status}}});return presentNews(await tx.news.findUniqueOrThrow({where:{id:n.id},include:relations}))})}
 async readable(id:string,user:Principal){const n=await this.detail(id,user);if(n.locked)throw new ForbiddenException('اشتراک ویژه لازم است.');return n}
}
@Controller('news')
export class NewsController{
 constructor(private service:NewsService,private db:Db){}
 @Public() @Get() list(@Query() q:any,@Req() req:any){return this.service.list(q,req.user)}
 @Public() @Get(':id') detail(@Param('id',ParseUUIDPipe) id:string,@Req() req:any){return this.service.detail(id,req.user)}
 @Permit('news:write') @Post() create(@Body() d:NewsDto,@Req() req:any){return this.service.write(d,req.user)}
 @Permit('news:write') @Patch(':id') edit(@Param('id',ParseUUIDPipe) id:string,@Body() d:NewsDto,@Req() req:any){return this.service.write(d,req.user,id)}
 @Permit('news:publish') @Delete(':id') async remove(@Param('id',ParseUUIDPipe) id:string,@Req() req:any){await this.db.$transaction([this.db.news.update({where:{id},data:{status:'ARCHIVED'}}),this.db.analytics.create({data:{event:'news.archived',newsId:id,userId:req.user.id}})]);return {ok:true}}
 @Post(':id/views') async view(@Param('id',ParseUUIDPipe) id:string,@Req() req:any){await this.service.readable(id,req.user);await this.db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM users WHERE id=${req.user.id}::uuid FOR UPDATE`;if(!await tx.analytics.findFirst({where:{userId:req.user.id,newsId:id,event:'view',createdAt:{gt:new Date(Date.now()-3600000)}}})){await tx.news.update({where:{id},data:{views:{increment:1}}});await tx.analytics.create({data:{event:'view',newsId:id,userId:req.user.id}})}});return {ok:true}}
 @Get(':id/comments') async comments(@Param('id',ParseUUIDPipe) id:string,@Req() req:any){await this.service.readable(id,req.user);return this.db.comment.findMany({where:{newsId:id},select:{id:true,body:true,createdAt:true,user:{select:{name:true}}},orderBy:{createdAt:'desc'},take:100})}
 @Post(':id/comments') async comment(@Param('id',ParseUUIDPipe) id:string,@Body() d:CommentDto,@Req() req:any){await this.service.readable(id,req.user);return this.db.comment.create({data:{newsId:id,userId:req.user.id,body:d.body}})}
 @Post(':id/reactions') async react(@Param('id',ParseUUIDPipe) id:string,@Req() req:any){await this.service.readable(id,req.user);return this.db.reaction.upsert({where:{newsId_userId:{newsId:id,userId:req.user.id}},create:{newsId:id,userId:req.user.id},update:{}})}
 @Delete(':id/reactions') async unreact(@Param('id',ParseUUIDPipe) id:string,@Req() req:any){await this.db.reaction.deleteMany({where:{newsId:id,userId:req.user.id}});return {ok:true}}
}
