import {Controller,Get,Post,Patch,Delete,Param,Req,Body,ParseUUIDPipe,ForbiddenException,BadRequestException,ServiceUnavailableException} from '@nestjs/common';
import {Db} from './db';import {Public,Permit} from './security';import {ProfileDto,EmployeeDto,MessageDto,ReplyDto,RoleDto,DeviceDto} from './dto';import {NewsService,presentNews,newsSummary} from './news';import {hasPermission} from './policy';
@Controller()
export class PlatformController{
 constructor(private db:Db,private news:NewsService){}
 async statistics(){const now=new Date();const [users,activeUsers,views,published,vipSubscribers,comments,reactions,popular]=await Promise.all([this.db.user.count(),this.db.user.count({where:{lastActiveAt:{gt:new Date(Date.now()-30*86400000)}}}),this.db.news.aggregate({_sum:{views:true}}),this.db.news.count({where:{status:'PUBLISHED'}}),this.db.subscription.findMany({where:{startsAt:{lte:now},expiresAt:{gt:now}},distinct:['userId'],select:{userId:true}}),this.db.comment.count(),this.db.reaction.count(),this.db.news.findMany({where:{status:'PUBLISHED'},orderBy:{views:'desc'},take:5,select:newsSummary})]);return {users,activeUsers,views:views._sum.views||0,published,vipSubscribers:vipSubscribers.length,comments,reactions,popular:popular.map(presentNews)}}
 @Public() @Get('health') async health(){await this.db.$queryRaw`SELECT 1`;return {status:'ok',service:'KhabarFori'}}
 @Public() @Get('home') async home(@Req() req:any){const recent=await this.news.list({limit:30},req.user);const saved=req.user?await this.db.bookmark.findMany({where:{userId:req.user.id},include:{news:{select:{categoryId:true}}},take:100}):[];const favoriteIds=[...new Set(saved.map(b=>b.news.categoryId))];const [featured,personalized,trending,announcements]=await Promise.all([this.db.news.findMany({where:{status:'PUBLISHED',featured:true},select:newsSummary,take:5,orderBy:{publishedAt:'desc'}}),favoriteIds.length?this.db.news.findMany({where:{status:'PUBLISHED',categoryId:{in:favoriteIds}},select:newsSummary,take:10,orderBy:{publishedAt:'desc'}}):[],this.db.tag.findMany({where:{news:{some:{news:{status:'PUBLISHED'}}}},include:{_count:{select:{news:true}}},take:10,orderBy:{news:{_count:'desc'}}}),this.db.setting.findUnique({where:{key:'announcements'}})]);return {featured:featured.map(presentNews),latest:recent.items,premium:recent.items.filter(n=>n.vip),personalized:personalized.map(presentNews),trending:trending.map(t=>({name:t.name,articles:t._count.news})),announcements:announcements?.value||[]}}
 @Public() @Get('workspace') async workspace(@Req() req:any){const user=req.user;const permitted=(p:string)=>user&&hasPermission(user.permissions,p);const [news,employees,messages,bookmarks,notifications,users,subscription,analytics]=await Promise.all([this.news.list({internal:'true',limit:100},user),permitted('employees:read')?this.employees():[],user?this.messages(req):[],user?this.db.bookmark.findMany({where:{userId:user.id},take:1000}):[],user?this.notifications(req):[],permitted('users:read')?this.users():[],user?this.db.subscription.findFirst({where:{userId:user.id,startsAt:{lte:new Date()},expiresAt:{gt:new Date()}},orderBy:{expiresAt:'desc'}}):null,permitted('analytics:read')?this.statistics():null]);return {demo:false,news:news.items,employees,messages,bookmarks:bookmarks.map(b=>b.newsId),profile:user?{id:user.id,name:user.name,email:user.email,roles:user.roles}:null,notifications,users,subscription,analytics}}
 @Get('profile') profile(@Req() req:any){return this.db.user.findUnique({where:{id:req.user.id},select:{id:true,name:true,email:true,phone:true,createdAt:true}})}
 @Patch('profile') updateProfile(@Req() req:any,@Body() d:ProfileDto){return this.db.user.update({where:{id:req.user.id},data:d,select:{id:true,name:true,email:true}})}
 @Permit('users:read') @Get('users') async users(){return (await this.db.user.findMany({take:100,orderBy:{createdAt:'desc'},select:{id:true,name:true,email:true,active:true,roles:{include:{role:true}}}})).map(u=>({...u,roles:u.roles.map(r=>r.role.name)}))}
 @Permit('users:manage') @Patch('users/:id/roles') async roles(@Param('id',ParseUUIDPipe) id:string,@Body() d:RoleDto,@Req() req:any){if(id===req.user.id)throw new BadRequestException('برای تغییر نقش خود از مدیر دیگری کمک بگیرید.');const roles=await this.db.role.findMany({where:{name:{in:d.roles}}});if(roles.length!==new Set(d.roles).size)throw new BadRequestException();await this.db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM roles WHERE name='SUPER_ADMIN' FOR UPDATE`;const target=await tx.userRole.findMany({where:{userId:id},include:{role:true}});if(target.some(r=>r.role.name==='SUPER_ADMIN')&&!d.roles.includes('SUPER_ADMIN')){const admins=await tx.userRole.count({where:{role:{name:'SUPER_ADMIN'},user:{active:true}}});if(admins<=1)throw new BadRequestException('حذف آخرین مدیر مجاز نیست.')}await tx.userRole.deleteMany({where:{userId:id}});await tx.userRole.createMany({data:roles.map(r=>({userId:id,roleId:r.id}))});await tx.user.update({where:{id},data:{tokenVersion:{increment:1}}});await tx.analytics.create({data:{event:'user.roles.changed',userId:req.user.id,metadata:{target:id,roles:d.roles}}})});return {ok:true}}
 @Permit('employees:read') @Get('employees') async employees(){return (await this.db.employee.findMany({include:{department:true},orderBy:{fullName:'asc'},take:500})).map(e=>({...e,department:e.department.name}))}
 @Permit('employees:write') @Post('employees') async employee(@Body() d:EmployeeDto){const {department,...data}=d;const dep=await this.db.department.findUniqueOrThrow({where:{name:department}});return this.db.employee.create({data:{...data,departmentId:dep.id}})}
 @Permit('employees:write') @Patch('employees/:id') async editEmployee(@Param('id',ParseUUIDPipe) id:string,@Body() d:EmployeeDto){const {department,...data}=d;const dep=await this.db.department.findUniqueOrThrow({where:{name:department}});return this.db.employee.update({where:{id},data:{...data,departmentId:dep.id}})}
 @Permit('employees:write') @Delete('employees/:id') async deleteEmployee(@Param('id',ParseUUIDPipe) id:string){await this.db.employee.delete({where:{id}});return {ok:true}}
 @Get('messages') async messages(@Req() req:any){return (await this.db.editorMessage.findMany({where:hasPermission(req.user.permissions,'messages:read')?{}:{userId:req.user.id},include:{user:{select:{name:true}}},orderBy:{createdAt:'desc'},take:100})).map(m=>({...m,sender:m.user.name}))}
 @Permit('messages:write') @Post('messages') message(@Req() req:any,@Body() d:MessageDto){return this.db.editorMessage.create({data:{...d,userId:req.user.id}})}
 @Permit('messages:reply') @Patch('messages/:id') async reply(@Param('id',ParseUUIDPipe) id:string,@Req() req:any,@Body() d:ReplyDto){return this.db.$transaction(async tx=>{const message=await tx.editorMessage.update({where:{id},data:{...d,repliedBy:req.user.id}});await tx.notification.create({data:{userId:message.userId,title:'پاسخ سردبیر',body:message.subject}});return message})}
 @Get('bookmarks') async bookmarks(@Req() req:any){return (await this.db.bookmark.findMany({where:{userId:req.user.id,news:{status:'PUBLISHED'}},include:{news:{select:newsSummary}},orderBy:{createdAt:'desc'},take:100})).map(b=>presentNews(b.news))}
 @Post('bookmarks/:id') async bookmark(@Param('id',ParseUUIDPipe) id:string,@Req() req:any){await this.news.detail(id,req.user);return this.db.bookmark.upsert({where:{userId_newsId:{userId:req.user.id,newsId:id}},update:{},create:{userId:req.user.id,newsId:id}})}
 @Delete('bookmarks/:id') async deleteBookmark(@Param('id',ParseUUIDPipe) id:string,@Req() req:any){await this.db.bookmark.deleteMany({where:{userId:req.user.id,newsId:id}});return {ok:true}}
 @Get('notifications') notifications(@Req() req:any){return this.db.notification.findMany({where:{userId:req.user.id},orderBy:{createdAt:'desc'},take:100})}
 @Post('notifications/read') async read(@Req() req:any){await this.db.notification.updateMany({where:{userId:req.user.id,readAt:null},data:{readAt:new Date()}});return {ok:true}}
 @Post('notifications/devices') async device(@Req() req:any,@Body() d:DeviceDto){const prior=await this.db.device.findUnique({where:{token:d.token}});if(prior&&prior.userId!==req.user.id)throw new ForbiddenException();return this.db.device.upsert({where:{token:d.token},update:{},create:{token:d.token,userId:req.user.id}})}
 @Permit('analytics:read') @Get('analytics') analytics(){return this.statistics()}
 @Permit('analytics:read') @Get('social') social(){return {connected:false,topics:[],message:'Configure a SocialProvider adapter with a verified business account.'}}
}
