import json
from pathlib import Path
schemas={
'Login':{'identifier':{'type':'string','description':'Email or E.164 phone'},'password':{'type':'string','minLength':12,'maxLength':72}},
'Register':{'identifier':{'type':'string'},'name':{'type':'string','minLength':2,'maxLength':100},'password':{'type':'string','minLength':12,'maxLength':72}},
'News':{'title':{'type':'string','minLength':3,'maxLength':200},'description':{'type':'string','minLength':3,'maxLength':500},'content':{'type':'string','minLength':3,'maxLength':100000},'category':{'type':'string','enum':['سیاست','اقتصاد','جامعه','فناوری','بین‌الملل','فرهنگ']},'status':{'type':'string','enum':['DRAFT','REVIEW','PUBLISHED']},'vip':{'type':'boolean'},'tags':{'type':'array','maxItems':20,'items':{'type':'string','maxLength':60}},'coverImage':{'type':'string','format':'uri'},'kind':{'type':'string','enum':['NEWS','EXPERT_OPINION','EDITOR_NOTE','EXCLUSIVE']}},
'Message':{'subject':{'type':'string','minLength':3,'maxLength':200},'body':{'type':'string','minLength':3,'maxLength':10000},'type':{'type':'string','enum':['MESSAGE','IDEA','REPORT','REVIEW']}},
'Reply':{'reply':{'type':'string','maxLength':10000},'status':{'type':'string','enum':['NEW','REVIEWING','COMPLETED']}},
'Employee':{'fullName':{'type':'string','minLength':2},'position':{'type':'string','minLength':2},'department':{'type':'string','enum':['مدیریت','تحریریه','خبرنگاری','روابط عمومی','فنی','پشتیبانی']},'biography':{'type':'string','maxLength':2000},'email':{'type':'string','format':'email'},'phone':{'type':'string'}},
'Roles':{'roles':{'type':'array','maxItems':6,'items':{'type':'string','enum':['SUPER_ADMIN','HOLDING_MANAGER','EDITOR_IN_CHIEF','EMPLOYEE','VIP_SUBSCRIBER','NORMAL_USER']}}},
'Profile':{'name':{'type':'string','minLength':2,'maxLength':100}},
'Password':{'currentPassword':{'type':'string'},'newPassword':{'type':'string','minLength':12,'maxLength':72}},
'Refresh':{'refreshToken':{'type':'string'}},'Forgot':{'identifier':{'type':'string'}},'Reset':{'token':{'type':'string'},'password':{'type':'string','minLength':12}},
'Checkout':{'planId':{'type':'string','enum':['monthly','quarterly','yearly']}},'Webhook':{'reference':{'type':'string'}},'Comment':{'body':{'type':'string','minLength':1,'maxLength':2000}},'Device':{'token':{'type':'string','minLength':20,'maxLength':4096}}
}
result={'openapi':'3.0.3','info':{'title':'KhabarFori API','version':'1.0.0','description':'Production NestJS contract. Internal permissions are enforced server-side. Monetary amounts are integer IRR.'},'servers':[{'url':'http://localhost:4000/api/v1'}],'security':[{'bearerAuth':[]}],'paths':{},'components':{'securitySchemes':{'bearerAuth':{'type':'http','scheme':'bearer','bearerFormat':'JWT'}},'schemas':{}}}
for name,props in schemas.items():result['components']['schemas'][name]={'type':'object','additionalProperties':False,'required':[k for k in props if k not in ['coverImage','kind','phone']],'properties':props}
endpoints=[
('post','/auth/register','Create account','Register','public'),('post','/auth/login','Authenticate','Login','public'),('post','/auth/refresh','Rotate refresh token','Refresh','public'),('post','/auth/logout','Revoke all own sessions',None,'signed-in'),('post','/auth/password','Change password','Password','signed-in'),('post','/auth/forgot-password','Request reset delivery','Forgot','public'),('post','/auth/reset-password','Redeem reset token','Reset','public'),
('get','/profile','Read own profile',None,'signed-in'),('patch','/profile','Update own name','Profile','signed-in'),('get','/news','Paginated news summaries',None,'public'),('get','/news/{id}','Read article or locked preview',None,'public'),('post','/news','Create news','News','news:write'),('patch','/news/{id}','Update news','News','news:write and ownership/editor rules'),('delete','/news/{id}','Archive news',None,'news:publish'),('post','/news/{id}/views','Deduplicated view count',None,'signed-in'),('get','/news/{id}/comments','Read article comments',None,'signed-in with article access'),('post','/news/{id}/comments','Post comment','Comment','signed-in with article access'),('post','/news/{id}/reactions','Like article',None,'signed-in with article access'),('delete','/news/{id}/reactions','Remove own like',None,'signed-in'),
('get','/bookmarks','Read own bookmarks',None,'signed-in'),('post','/bookmarks/{id}','Bookmark news',None,'signed-in'),('delete','/bookmarks/{id}','Remove bookmark',None,'signed-in'),('get','/home','Reader home and personalization',None,'public'),('get','/workspace','Permission-filtered aggregate',None,'public'),('get','/users','List users',None,'users:read'),('patch','/users/{id}/roles','Replace role grants','Roles','users:manage'),('get','/employees','Read internal directory',None,'employees:read'),('post','/employees','Create employee','Employee','employees:write'),('patch','/employees/{id}','Update employee','Employee','employees:write'),('delete','/employees/{id}','Delete employee',None,'employees:write'),('get','/messages','Read own messages or editor inbox',None,'signed-in'),('post','/messages','Contact editor','Message','messages:write'),('patch','/messages/{id}','Reply and update status','Reply','messages:reply'),('get','/subscriptions/plans','List active plans',None,'public'),('post','/subscriptions/checkout','Create idempotent checkout','Checkout','signed-in'),('post','/subscriptions/webhook','Verify provider callback','Webhook','public'),('get','/subscriptions/status','Read active entitlement',None,'signed-in'),('get','/subscriptions/payments','Read payment history',None,'signed-in'),('get','/notifications','Read own notifications',None,'signed-in'),('post','/notifications/read','Mark own notifications read',None,'signed-in'),('post','/notifications/devices','Register FCM device','Device','signed-in'),('post','/media','Upload verified cover image',None,'news:write'),('get','/analytics','Read monitoring aggregates',None,'analytics:read'),('get','/social','Read social provider state',None,'analytics:read'),('get','/health','Database readiness',None,'public')]
for method,path,summary,schema,access in endpoints:
 op={'summary':summary,'operationId':method+'_'+path.strip('/').replace('/','_').replace('{','').replace('}',''),'tags':[path.split('/')[1]],'x-required-permission':access,'responses':{('201' if method=='post' else '200'):{'description':'Success; see API.md for the response shape'},'400':{'description':'Validation failure'},'401':{'description':'Missing/invalid session'},'403':{'description':'Permission or entitlement denied'},'404':{'description':'Not found or hidden draft'},'429':{'description':'Rate limit exceeded'},'503':{'description':'Required integration unavailable'}}}
 if access=='public':op['security']=[]
 if schema:op['requestBody']={'required':True,'content':{'application/json':{'schema':{'$ref':'#/components/schemas/'+schema}}}}
 if '{id}' in path:op['parameters']=[{'name':'id','in':'path','required':True,'schema':{'type':'string','format':'uuid'}}]
 if path=='/news' and method=='get':op['parameters']=[{'name':name,'in':'query','schema':({'type':'integer','minimum':1,'maximum':100} if name=='limit' else {'type':'string'})} for name in ['limit','cursor','category','q','vip','internal']]
 if path=='/subscriptions/checkout':op['parameters']=[{'name':'Idempotency-Key','in':'header','required':True,'schema':{'type':'string','minLength':16,'maxLength':128}}]
 if path=='/subscriptions/webhook':op['parameters']=[{'name':'X-Payment-Signature','in':'header','required':True,'schema':{'type':'string','pattern':'^[a-fA-F0-9]{64}$'}}]
 if path=='/media':op['requestBody']={'required':True,'content':{'multipart/form-data':{'schema':{'type':'object','required':['file'],'properties':{'file':{'type':'string','format':'binary','description':'JPEG, PNG or WebP, maximum 5 MiB'}}}}}}
 result['paths'].setdefault(path,{})[method]=op
Path('docs/openapi.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
print(f'Generated OpenAPI contract: {len(endpoints)} operations')
